### ISSUE TITLE
Can these scripts be invoked from python directly ?

### ISSUE THREAD

**Issue by sariths** [gmischler/PyRad#1]
Hi @gmischler , I was trying to test your scripts when I noticed that at present, the file won't work unless it is frozen as an executable (https://github.com/gmischler/PyRad/blob/master/scripts/falsecolor.py#L14-L23). Are these scripts only meant to be used as command line programs?

**Comment by gmischler** [comment]
Hi @sariths,

the scripts don't need to be frozen. The lines you refer to make sure they will find the support files when _not_ frozen (in frozen state, the support files are included and will always be found).

But they are indeed designed to only work from the command line at the moment. The reason for this is that the API of the class is very simple and has no error checking. That makes it unsuitable for exterenal use.

**Comment by sariths** [comment]
Hi, @gmischler Thank you for the explanation. Your use of `for-else` and `sys.exit` threw me off a bit. I normally work inside the python environment and am used to raising Exceptions instead of exiting. 

Anyways, I wrote a quick hack to run your scripts through os.system so that I can still stay inside Python. https://github.com/sariths/PyRad/blob/master/test.py. Are you planning to expand these scripts to other Radiance shell-scripts and perl-scripts as well? 

I am used to writing wrapper scripts for Python/Radiance the instead of writing re-implementations like you are creating here (as I don't know much about what goes on 'under the hood' w.r.t Radiance). Let me know if you are looking for collaborators. I will be glad to pitch in whatever capacity I can.

Sarith

**Comment by gmischler** [comment]
Hi @sariths,
the goal is to create Python implementations for all the most commonly used scripts in Radiance, and to include those in the distribution. There have been discussions about that on the radiance-dev mailing list. So yes, we need more of them, and all kinds of contributions are welcome.

**Comment by sariths** [comment]
@gmischler Do you have a TODO list of scripts that you are planning to work on? Secondly, how do you usually go about writing these scripts? Do you read the c-shell or perl scripts or do you just write them from experience (and knowledge of Radiance)?. I have been working with Radiance for the past three years or so. I understand that your experience in Radiance exceeds mine by at least a couple of decades. So, I was wondering if there was a way for someone like me to get started with writing these scripts.

**Comment by gmischler** [comment]
Hi @sariths,
there is no formal todo list. On the radiance-dev list, objview and friends have been asked for. Other than that, its up to contributors to make their choices. The dev-list would be a good place to coordinate such plans.
I've just updated the design recommendations in the doc folder. For the actual functionality, the original code is the most useful to follow. We also need tests that can show that both the original and the replacement produce the same output.
There are some newer scripts, eg. for data conversion, where I'm also not familiar with those data formats. In those cases we need example data to test on.

**Comment by sariths** [comment]
Hi @gmischler, Thank you. If you aren't working on that already I am going to try to implement objview within your framework and design guidelines. I currently do something like "Popen.. perl-path...objview.pl...radFiles" on my windows machine. So having a python implementation would be good for my own work too. I will hopefully make some progress by this weekend.

I am going to close this issue and open a new one for Objview. I will keep that one open till I can make a commit and send a pull request to your repository.

Sarith
