### ISSUE TITLE
Possible inheritance issue with Pveil.

### ISSUE THREAD

**Issue by sariths** [gmischler/PyRad#3]
Hi @gmischler , I was trying to understand your code when I came across [this](https://github.com/gmischler/PyRad/blob/master/scripts/pveil.py#L34). shouldn't `Pveil`be inheriting from `ProcMixin`. I don't see any other way that the method [here](https://github.com/gmischler/PyRad/blob/master/scripts/pveil.py#L48) will be legal.

**Comment by gmischler** [comment]
Pveil.py was rather out of date, it had some other problems as well.
I didn't pay much attention to it for a while, since the original pveil.csh is undocumented and normally doesn't even get installed.
But I think I've fixed it now.
